config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.includes(:root)
    @taxon = Spree::Taxon.find(params[:id])
    @taxon_products = Spree::Product.in_taxons(@taxon).includes(:master, :variants)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = 'BIGBAG Store'.freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= render "layouts/shared/header" %>
    <%= render "layouts/shared/header_light_section", page_title: yield(:title) %>
    <%= yield %>
    <%= render "layouts/shared/modal" %>
    <%= render "layouts/shared/footer_light_section" %>
    <%= render "layouts/shared/footer" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_footer_light_section.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/shared/_header.html.erb
<div class="header clearfix">
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", class: "navbar-brand"), potepan_index_path %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active">
            <%= link_to 'Home', potepan_index_path %>
          </li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="truaria-expanded="false">Shop</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/shared/_header_light_section.html.erb
<% provide(:title, page_title) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= page_title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><%= link_to "Home", potepan_index_path %></li>
          <li><%= link_to "Shop", '#' %></li>
          <li class="active"><%= page_title %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/shared/_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_category_children_list.html.erb
<li>
  <%= link_to "javascript:;", data: {toggle:"collapse", target: "##{category_children_list.id}" }, class: 'collapse_toggle' do %>
    <%= category_children_list.name %>
    <i class="fa fa-plus"></i>
  <% end %>
  <ul id="<%= category_children_list.id %>" class="collapse collapseItem">
    <% category_children_list.root.leaves.each do |sub_category| %>
      <li>
        <%= link_to potepan_category_path(sub_category.id) do %>
          <i class="fa fa-caret-right" aria-hidden="true"></i>
          <%= sub_category.name %> <span>(<%= sub_category.products.count %>)</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/_color_category_list.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_grid_show.html.erb
<div class="row taxon_product_box">
  <% taxon_product.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment.url, :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
    <%= render 'layouts/shared/modal' %>
  <% end %>
</div>

app/views/potepan/categories/_product_category_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav category_nav">
        <%= render partial: 'category_children_list', collection: taxonomies %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_size_category_list.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar"> 
        <%= render 'product_category_list', taxonomies: @taxonomies %>
        <%= render 'color_category_list' %>
        <%= render 'size_category_list' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'filter_area' %>
        <%= render 'grid_show', taxon_product: @taxon_products %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, index| %>
                  <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                    <%= image_tag(image.attachment(:product)) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag image.attachment(:small) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><i class="fa fa-reply" aria-hidden="true"></i>
              <%= link_to '一覧ページへ戻る', potepan_category_path(@product.taxons.first.id) %></li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag "/assets/products-01.jpg" %>
          </div>
          <div class="productCaption clearfix">
           <h5>Nike Sportswear</h5>
           <h3>199円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag "/assets/products-02.jpg" %>
          </div>
          <div class="productCaption clearfix">
           <h5>Dip Dyed Sweater</h5>
           <h3>249円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag "/assets/products-03.jpg" %>
          </div>
          <div class="productCaption clearfix">
           <h5>Scarf Ring Corner</h5>
           <h3>179円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag "/assets/products-04.jpg" %>
          </div>
          <div class="productCaption clearfix">
           <h5>Sun Buddies</h5>
           <h3>149円</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/blog_single_left_sidebar.html.erb
      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2>Blog Single sidebar</h2>
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">Blog Single sidebar</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix blogPage singleBlog">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4 col-xs-12">
              <div class="row">
                <div class="col-xs-12">
                  <div class="thumbnail">
                    <%= image_tag("img/blog/blog-01.jpg", :alt => "blog-image") %>
                    <div class="caption">
                      <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <h3>記事タイトル </h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                          <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>

                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                          <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                        </div>
                      </div>
                    </div>
                    <ul class="pager">
                      <li class="previous"><a href="#">前の記事へ</a></li>
                      <li class="next"><a href="#">次の記事へ</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12 sideBar">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
                <a href="#" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></a>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading">カテゴリー</div>
                <div class="panel-body">
                  <ul class="list-unstyle sidebar-list">
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>アクセサリー <span>(6)</span></a></li>
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>バッグ <span>(6)</span></a></li>
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>洋服 <span>(25)</span></a></li>
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>ベッド &amp; バス <span>(2)</span></a></li>
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スイミング <span>(5)</span></a></li>
                    <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スポーツウェア &amp; シューズ <span>(3)</span></a></li>
                  </ul>
                </div>
              </div>
              <div class="panel panel-default recentBlogPosts">
                <div class="panel-heading">最新記事</div>
                <div class="panel-body">
                  <div class="media">
                    <a class="media-left" href="blog_single_right_sidebar.html">
                      <%= image_tag("img/blog/blog-small-01.jpg", :class => "media-object", :alt => "Image") %>
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                    </div>
                  </div>
                  <div class="media">
                    <a class="media-left" href="blog_single_right_sidebar.html">
                      <%= image_tag("img/blog/blog-small-02.jpg", :class => "media-object", :alt => "Image") %>
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                    </div>
                  </div>
                  <div class="media">
                    <a class="media-left" href="blog_single_right_sidebar.html">
                      <%= image_tag("img/blog/blog-small-03.jpg", :class => "media-object", :alt => "Image") %>
                    </a>
                    <div class="media-body">
                      <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
   